package com.intellij.lang.parser;

/**
 * ONLY PLACEHOLDER.
 * Parser generated by GrammarKit references class with such qualified name by default.
 * Unfortunately, due to some development error light-psi-all.jar contains this class in package
 * org.intellij.grammar.parser. Use it instead - just replace in generated parser this:
 *     import static com.intellij.lang.parser.GeneratedParserUtilBase.*;
 * with this:
 *     import static org.intellij.grammar.parser.GeneratedParserUtilBase.*;
 * 
 * @see org.intellij.grammar.parser.GeneratedParserUtilBase
 */
public class GeneratedParserUtilBase extends org.intellij.grammar.parser.GeneratedParserUtilBase
{
}